spring:
    application:
        name: hackaton-gateway
    cloud:
        gateway:
            routes:
                - id: hackaton-clientes-app
                  uri: lb://hackaton-clientes-app
                  predicates:
                      - Path=/api/cliente/**
                  filters:
                      - AuthenticationFilter


                - id: hackaton-cartao-app
                  uri: lb://hackaton-cartao-app
                  predicates:
                      - Path=/api/cartao/**
                  filters:
                      - AuthenticationFilter


                - id: hackaton-pagamentos-app
                  uri: lb://hackaton-pagamentos-app
                  predicates:
                      - Path=/api/pagamentos/**
                  filters:
                      - AuthenticationFilter


                - id: hackaton-autenticacao-app
                  uri: lb://hackaton-autenticacao-app
                  predicates:
                      - Path=/api/autenticacao/**


eureka:
    client:
        service-url:
            defaultZone : http://localhost:8761/eureka/